package com.wellness.Entity;

public enum QuestionCode {
    TODAY_ENERGY,
    LAST_NIGHT_SLEEP,
    SKIN_STATUS,
    CARE_AVAILABLE_TIME,
    TODAY_PLANNED_CARE,
    STRENGTH_TRAINING_FREQUENCY,
    CARDIO_FREQUENCY,
    PILATES_FREQUENCY,
    SUPPLEMENTS,
    WATER_INTAKE,
    SKIN_TYPE,
    SKIN_CONCERN,
    SKINCARE_VISIT_FREQUENCY
}
