package com.wellness.Entity;

public enum QuestionCode {
    TODAY_ENERGY,
    LAST_NIGHT_SLEEP,
    SKIN_STATUS,
    CARE_AVAILABLE_TIME,
    TODAY_PLANNED_CARE,
    HARDEST_MOMENT,
    STRENGTH_TRAINING,
    CARDIO,
    STRETCHING,
    SUPPLEMENTS,
    WATER_INTAKE,
    SKIN_TYPE,
    SKIN_CONCERN,
    SKINCARE_FREQUENCY
}
